version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "05:00"
      timezone: "Europe/Berlin"
    assignees:
      - "DEVTomatoCake"
    groups:
      eslint-html-parser:
        patterns:
          - "@html-parser/eslint-plugin"
          - "@html-parser/parser"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "05:00"
      timezone: "Europe/Berlin"
